initial_positions:
  joint1: 0.0
  joint2: 0.0
  joint3: 0.0
  joint4: 0.0
  joint5: 0.0
  joint6: 0.0
  joint7: 0.0
  gripper_joint1: 0.0
  gripper_joint2: 0.0
  left_thumb_metacarpal_joint: 0.0
  left_thumb_proximal_joint: 0.0
  left_index_proximal_joint: 0.0
  left_middle_proximal_joint: 0.0
  left_ring_proximal_joint: 0.0
  left_pinky_proximal_joint: 0.0
  right_thumb_metacarpal_joint: 0.0
  right_thumb_proximal_joint: 0.0
  right_index_proximal_joint: 0.0
  right_middle_proximal_joint: 0.0
  right_ring_proximal_joint: 0.0
  right_pinky_proximal_joint: 0.0
